spring.datasource.url=${SAHA_POSTGRES_URL:jdbc:postgresql://localhost:5432/sahaDB}
spring.datasource.username=${SAHA_POSTGRES_USERNAME:saha}
spring.datasource.password=${SAHA_POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
